apiVersion: cluster.appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: "SPOT_ON_Secure_CN_Cluster"
  controllerUrl: "https://devnet.saas.appdynamics.com"
  account: "devnet"
  # docker image info
  image: "docker.io/appdynamics/cluster-agent:21.12.0"
  serviceAccountName: appdynamics-cluster-agent
  #
  # auto-instrumentation config
  #
  instrumentationMethod: Env
  nsToInstrumentRegex: sock-shop
  appNameStrategy: namespace
  instrumentationRules:
    - namespaceRegex: sock-shop
      language: java
      labelMatch:
        - framework: java
      imageInfo:
        image: "docker.io/appdynamics/java-agent:21.3.0"
        agentMountPath: /opt/appdynamics
        imagePullPolicy: "IfNotPresent"