# AppDynamics controller info
# controllerInfo values are declared in terraform-appd-cluster-agent.tf
imageInfo:
  agentImage: docker.io/appdynamics/cluster-agent
  agentTag: 21.12.0
  operatorImage: docker.io/appdynamics/cluster-agent-operator
  operatorTag: latest
  imagePullPolicy: Always

  # Cluster agent config
clusterAgent:
  nsToMonitor: [default,kube-node-lease,kube-public,kube-system,appdynamics,sock-shop]